
import { Shirt, Tv, Sofa, Smartphone, Blender, BookOpen, ToyBrick } from 'lucide-react';

export const products = [
    {
        id: "1",
        name: "Kemeja Lengan Panjang Pria",
        price: 185000,
        originalPrice: 250000,
        promotion: 'Flash Sale',
        image: "https://placehold.co/300x300.png",
        hint: "men shirt",
        sold: 88,
        stock: 12,
    },
    {
        id: "2",
        name: "Gaun Pesta Wanita Elegan",
        price: 320000,
        image: "https://placehold.co/300x300.png",
        hint: "elegant dress",
    },
    {
        id: "3",
        name: "Smart TV 4K 55 Inci",
        price: 5500000,
        image: "https://placehold.co/300x300.png",
        hint: "smart tv",
    },
    {
        id: "4",
        name: "Sofa Minimalis Ruang Tamu",
        price: 2750000,
        promotion: 'Best Seller',
        image: "https://placehold.co/300x300.png",
        hint: "living room sofa",
    },
    {
        id: "5",
        name: "Blender Multifungsi Cepat",
        price: 450000,
        originalPrice: 600000,
        promotion: 'Flash Sale',
        image: "https://placehold.co/300x300.png",
        hint: "kitchen blender",
        sold: 120,
        stock: 30,
    },
    {
        id: "6",
        name: "Smartphone Gaming Terbaru",
        price: 4200000,
        image: "https://placehold.co/300x300.png",
        hint: "gaming smartphone",
    },
    {
        id: "7",
        name: "Buku Novel Fiksi Terlaris",
        price: 95000,
        image: "https://placehold.co/300x300.png",
        hint: "fiction novel book",
    },
    {
        id: "8",
        name: "Mainan Edukasi Anak Balok",
        price: 150000,
        promotion: 'Best Seller',
        image: "https://placehold.co/300x300.png",
        hint: "kids educational toy",
    },
     {
        id: "9",
        name: "Headphone Bluetooth Kedap Suara",
        price: 750000,
        originalPrice: 900000,
        promotion: 'Flash Sale',
        image: "https://placehold.co/300x300.png",
        hint: "bluetooth headphones",
        sold: 50,
        stock: 50,
    },
    {
        id: "10",
        name: "Sepatu Lari Pria Nyaman",
        price: 650000,
        image: "https://placehold.co/300x300.png",
        hint: "men running shoes",
    },
];

export const categories = [
  { name: "Pakaian Pria", icon: Shirt },
  { name: "Pakaian Wanita", icon: Shirt },
  { name: "Elektronik", icon: Tv },
  { name: "Perabotan", icon: Sofa },
  { name: "Handphone", icon: Smartphone },
  { name: "Peralatan Dapur", icon: Blender },
  { name: "Buku & Alat Tulis", icon: BookOpen },
  { name: "Mainan & Hobi", icon: ToyBrick },
];
